Handling Universally Unique Identifiers (UUIDs)
-----------------------------------------------

The uuid module is used to generate and parse uuids. It uses the libuuid by
Theodore Y. Ts'o. libuuid is part of the util-linux package since version
2.15.1 and is available from ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
This documentation is therefore based on the libuuid documentation.

The UUID is internally 16 bytes (128  bits) long, which gives approximately
3.4x10^38 unique values (there are approximately 10^80 elementary particles in
the universe according to Carl Sagan's Cosmos). The new UUID can reasonably
be considered unique among all UUIDs created on the local system, and among
UUIDs created on other systems in the past and in the future.

UUID Generating Functions
~~~~~~~~~~~~~~~~~~~~~~~~~

generate([format])
^^^^^^^^^^^^^^^^^^

The *generate* function creates a new uuid. The uuid will be generated based
on high-quality randomness from  /dev/urandom, if available. If it is not
available, then *generate* will use an alternative algorithm which uses the
current time, the local ethernet MAC address (if available), and random data
generated using a pseudo-random generator.

If the optional parameter format is the string 't', then uuid will be returned
as a string, otherwise it will be returned as a uuid object with a proper
metatable.

generate_random([format])
^^^^^^^^^^^^^^^^^^^^^^^^^

The *generate_random() function forces the use of the all-random UUID
format, even if a high-quality random number generator (i.e.,
/dev/urandom) is not available, in which case a pseudo-random generator
will be substituted. Note that the use of a pseudo-random  generator
may compromise the uniqueness of UUIDs generated in this fashion.

generate_time([format])
^^^^^^^^^^^^^^^^^^^^^^^

The *generate_time* function forces the use of the alternative algorithm which
uses the current time and the local ethernet MAC address (if available).
This algorithm used to be the default one used to generate UUID, but because
of the use of the ethernet MAC address, it can leak information about when
and where the UUID was generated. This can cause privacy problems in some
applications, so the *generate* function only uses this algorithm if a
high-quality source of randomness is not available. To guarantee uniqueness
of UUIDs generated by concurrently running processes, the underlying uuid
library uses a global clock state counter (if the process has permissions to
gain exclusive access to this file) and/or the uuidd daemon, if it is running
already or can be spawned by the process (if installed and the process has
enough permissions to run it). If neither of these two synchronization
mechanisms can be used, it is theoretically possible that two concurrently
running processes obtain the same UUID(s). To tell whether the UUID has been
generated in a safe manner, use *generate_time_safe*.

generate_time_safe([format])
^^^^^^^^^^^^^^^^^^^^^^^^^^^

The *generate_time_safe* is similar to *generate_time*,  except
that  it  returns a value which denotes whether any of the synchronization
mechanisms (see above) has been used.

parse(string)
^^^^^^^^^^^^^

The *parse* function converts the UUID string into a uuid.
The input UUID is a string of the form 967c2ed8-7903-4ace-8a27-97daf7f63097 (in
string.format() format "%08x-%04x-%04x-%04x-%012x", 36 bytes.)

UUID functions
~~~~~~~~~~~~~~

uuid:clear()
^^^^^^^^^^^^

Clear the memory used by a uuid object.  This is usuall called by the Lua
garbage collector.

uuid:compare(uuid2)
^^^^^^^^^^^^^^^^^^

Compare uuid to uuid2. Returns an integer less than, equal to, or greater than
zero if uuid lexicographically less than, equal, or greater than uuid2.

is_null(uuid)
^^^^^^^^^^^^^

The *is_null* function compares the value of the supplied UUID object
uuid to the NULL value. If the value is equal to the NULL UUID, true
is returned, otherwise false is returned.

time(uuid)
^^^^^^^^^^

The *time* function extracts the time at which the supplied timebased UUID
uuid was created. Note that the UUID creation time is only
encoded within certain types of UUIDs. This function can only reasonably
be expected to extract the creation time for UUIDs created with the
*generate_time()* and *generate_time_safe()* functions. It may
or may not work with UUIDs created by other mechanisms.

The *time* functions returns two integers, the seconds value and the
microseconds value.

unparse(uuid)
^^^^^^^^^^^^^

The *unparse* function converts the supplied UUID uuid from the binary
representation into a 36-byte string of the form
967c2ed8-7903-4ace-8a27-97daf7f63097. The case of the hex digits returned by
*unparse* may be upper or lower case, and is dependent on the system-dependent
local default.

Metamethods
~~~~~~~~~~~

The following metamethods are defined for uuuids.

__eq
^^^^

The == operation.  Test if two uuid are equal.

__lt
^^^^

The < operation.  Test if one uuid is less than another

__le
^^^^

The <= operator.  Test if one uuid is less or equal than another.

__tostring
^^^^^^^^^^

Convert a uuid to its string representation.

__concat
^^^^^^^^

Concatenate a uuid.

__len
^^^^^

Then length operator #.  This returns the length in bytes of the textual
representation of the uuid.
